name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install spex
        run: npm install -g spex@0.32.0

      - name: Spex validate
        run: spex validate export
